apiVersion: apps/v1
kind: Deployment
metadata:
  name: trending-service
spec:
  selector:
    matchLabels:
      app: trending-service
  template:
    metadata:
      labels:
        app: trending-service
    spec:
      containers:
        - image: trending-service
          name: trending-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: trending-service
spec:
  type: NodePort
  selector:
    app: trending-service
  ports:
    - port: 8080
      targetPort: 8080