apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: insecure
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - image: auth-service
          name: auth-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: { }
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: insecure
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 8080
      targetPort: 8080