apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
spec:
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
        - image: example-service
          name: example-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: { }
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  selector:
    app: example-service
  ports:
    - port: 8080
      targetPort: 8080