echo "## Building Image $1 ##"
echo "> docker build --tag $1 --file fp/services/$1/deploy/docker/Dockerfile fp/services/$1"
docker build --tag $1 --file "../fp/services/$1/deploy/docker/Dockerfile" "../fp/services/$1"
echo "## Deploying $1 ##"
./deploy_to_kubernetes.sh "../fp/services/$1/deploy/k8s/deployment.yml"